[package]
name = "time-kit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

tokio = ["tokio-runtime"]
async-std = ["async-std-runtime"]
smol = ["smol-runtime"]

[dependencies]
thiserror = "1.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# Optional dependencies
tokio-runtime = { package = "tokio", version = "1.0", features = ["time"], optional = true }
async-std-runtime = { package = "async-std", version = "1.0", optional = true }
smol-runtime = { package = "smol", version = "1.0", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
# Optional dependencies
wasm-timer = { version = "0.2", optional = true }